### PR TITLE
add a simpeg badge!

### PR DESCRIPTION
**Pull request by lheagy**
image

### CODE REVIEW

**Comment by rowanc1** [comment]
👍

**Comment by fourndo** [comment]
oh I like that. 
i m gonna put one of those right now

**Comment by fourndo** [comment]
ooops. Travis is not happy with the external file

Warning, treated as error:

/home/travis/build/ubcgif/gpg/content/magnetics/magnetics_interpretation.rst:None: WARNING: nonlocal image URI found: https://img.shields.io/badge/powered%20by-SimPEG-blue.svg

**Comment by rowanc1** [comment]
https://github.com/simpeg/simpeg/blob/master/docs/conf.py#L268

**Pull request merged**
